["MyCircularDeque","insertLast","insertLast","insertFront","insertFront","getRear","isFull","deleteLast","insertFront","getFront"]
[[3],[1],[2],[3],[4],[],[],[],[4],[]]
["MyCircularDeque","insertFront","insertFront","insertFront","deleteLast","deleteLast","deleteLast"]
[[3],[1],[2],[3],[],[],[]]
["MyCircularDeque","insertLast","insertLast","insertLast","deleteFront","deleteLast","deleteFront"]
[[3],[1],[2],[3],[],[],[]]
["MyCircularDeque","insertLast","insertLast","insertLast","deleteLast","deleteLast","deleteLast", "deleteLast"]
[[3],[1],[2],[3],[],[],[],[]]
["MyCircularDeque","insertFront","insertFront","insertFront","deleteLast","deleteLast","deleteLast", "deleteLast"]
[[3],[1],[2],[3],[],[],[],[]]
["MyCircularDeque","insertFront","insertLast","getRear","getFront","getFront","deleteLast","deleteFront","getRear"]
[[41],[70],[11],[],[],[],[],[],[]]
["MyCircularDeque","insertFront","insertFront","getRear","getFront","getFront","deleteLast","deleteFront","getRear"]
[[41],[70],[11],[],[],[],[],[],[]]
["MyCircularDeque","insertFront","insertLast","deleteFront","getFront","deleteLast","insertLast","isEmpty","deleteLast","insertFront","getRear","deleteFront","insertFront","insertLast","deleteLast","getFront","getRear","insertFront","getRear","getFront"]
[[999],[93],[578],[],[],[],[533],[],[],[913],[],[],[100],[57],[],[],[],[900],[],[]]